import './global.css';
import { Layouts } from '@org/ui';

export const metadata = {
  title: 'Welcome to media-plan',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layouts.FullWidth>
          {children}
        </Layouts.FullWidth>
      </body>
    </html>
  );
}
